 const productsAction = {
   FETCH_PRODUCTS_GET: "FETCH_PRODUCTS_GET",
   FETCH_PRODUCT_CREATE: "FETCH_PRODUCT_CREATE",
   FETCH_PRODUCT_DELETE: "FETCH_PRODUCT_DELETE",
   FETCH_PRODUCT_UPDATE: "FETCH_PRODUCT_UPDATE",
 };
export default productsAction
